"""added_phone_number_to_patient_model

Revision ID: 40c2d862bdee
Revises: 0bcfa74c71b1
Create Date: 2026-06-16 00:04:36.680203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c2d862bdee'
down_revision: Union[str, Sequence[str], None] = '0bcfa74c71b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('phone_number', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'phone_number')
    # ### end Alembic commands ###
