"""adeded phone number to patient model


Revision ID: 46285144a807
Revises: 93718db55a7d
Create Date: 2026-06-15 23:55:10.677751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46285144a807'
down_revision: Union[str, Sequence[str], None] = '93718db55a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intakes_id'), table_name='intakes')
    op.drop_table('intakes')
    op.drop_index(op.f('ix_clinic_users_email'), table_name='clinic_users')
    op.drop_index(op.f('ix_clinic_users_id'), table_name='clinic_users')
    op.drop_index(op.f('ix_clinic_users_username'), table_name='clinic_users')
    op.drop_table('clinic_users')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date_of_birth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preferred_language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('intake_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('emergency_contact_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emergency_contact_phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('insurance_provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('insurance_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['clinic_users.id'], name=op.f('patients_provider_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('patients_pkey')),
    sa.UniqueConstraint('email', name=op.f('patients_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('clinic_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('clinic_users_pkey'))
    )
    op.create_index(op.f('ix_clinic_users_username'), 'clinic_users', ['username'], unique=True)
    op.create_index(op.f('ix_clinic_users_id'), 'clinic_users', ['id'], unique=False)
    op.create_index(op.f('ix_clinic_users_email'), 'clinic_users', ['email'], unique=True)
    op.create_table('intakes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_edited', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('intakes_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('intakes_pkey'))
    )
    op.create_index(op.f('ix_intakes_id'), 'intakes', ['id'], unique=False)
    # ### end Alembic commands ###
